steps:
  # Build the main bot service image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/therapist-o3/therapist-bot:$COMMIT_SHA',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/therapist-o3/therapist-bot:latest',
      '-f', 'Dockerfile',
      '.'
    ]
    id: 'build-bot'

  # Push the bot image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/$PROJECT_ID/therapist-o3/therapist-bot:$COMMIT_SHA'
    ]
    waitFor: ['build-bot']
    id: 'push-bot'

  # Push the bot latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/$PROJECT_ID/therapist-o3/therapist-bot:latest'
    ]
    waitFor: ['build-bot']
    id: 'push-bot-latest'

  # Deploy the main bot service to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'therapist-o3',
      '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/therapist-o3/therapist-bot:$COMMIT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--memory', '1Gi',
      '--cpu', '1',
      '--min-instances', '0',
      '--max-instances', '10',
      '--set-env-vars', 'TESTING=False'
    ]
    waitFor: ['push-bot']
    id: 'deploy-bot'

  # Set webhook after successful bot deployment
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Get the service URL
        SERVICE_URL=$(gcloud run services describe therapist-o3 --region=us-central1 --format="value(status.url)")
        echo "Service URL: $SERVICE_URL"
        
        # Set the webhook using Python script
        python3 scripts/set_webhook.py --url "$SERVICE_URL/webhook"
    waitFor: ['deploy-bot']
    id: 'set-webhook'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Timeout for the entire build
timeout: '1200s'

# Substitutions for environment variables
substitutions:
  _REGION: 'us-central1'
  _REPOSITORY: 'therapist-o3' 