name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual CI run'
        required: false
        default: 'Manual CI run'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Scan for committed credentials
      run: |
        if ls *-firebase-adminsdk*.json 1> /dev/null 2>&1 || ls *-sa.json 1> /dev/null 2>&1 || ls *.private.*json 1> /dev/null 2>&1 || ls credentials.json 1> /dev/null 2>&1 || ls serviceAccountKey.json 1> /dev/null 2>&1; then
          echo "ERROR: Committed credential file found! Please remove any service account JSON files from the repository."
          echo "Ensure they are covered by .gitignore and managed via GitHub Secrets instead."
          exit 1
        else
          echo "No credential files found. Proceeding."
        fi

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest
      env:
        TESTING: 'True'
        TELEGRAM_TOKEN: 'test_token'
        OPENAI_API_KEY: 'test_key'
        FIREBASE_PROJECT_ID: 'test_project' 